- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/sst/ocean_current"
  gz_topic_name: "/model/sst/ocean_current"
  ros_type_name: "geometry_msgs/msg/Vector3"
  gz_type_name: "gz.msgs.Vector3d"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS    # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/sst/joint_states"
  gz_topic_name: "/world/ocean/model/sst/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS    # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/tf"
  gz_topic_name: "/model/sst/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/sst/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz
# Note: QoS override for /tf_static is set in the launch file:
# Parameter: qos_overrides./tf_static.publisher.durability
# Value: transient_local

- ros_topic_name: "/odometry"
  gz_topic_name: "/model/sst/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/sst/imu"
  gz_topic_name: "/model/sst/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/sst/dvl/velocity_notStamped"
  gz_topic_name: "/model/sst/dvl_ros_compatible/velocity"
  ros_type_name: "geometry_msgs/msg/TwistWithCovariance"
  gz_type_name: "gz.msgs.TwistWithCovariance"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/sst/dvl/range"
  gz_topic_name: "/model/sst/dvl_ros_compatible/range"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

